USE heredoc for variable exporting

diff --git a/bin/kireisakura b/bin/kireisakura
--- a/bin/kireisakura
+++ b/bin/kireisakura
@@ -188,6 +188,18 @@ update_kit() {
   fi
 }
 
+run_tester() {
+  echo -e "\n${LAVENDER}================= KireiSakura Kit Test Utility ==================${NC}\n"
+
+  if bash "$lib_dir/_test.sh"; then
+    echo -e "\n\n${GREEN}================ TEST SUCCESSFULLY COMPLETED ==================${NC}\n"
+    exit 0
+  else
+    echo -e "\n\n${RED}================== TEST FAILED ==================${NC}\n"
+    exit 1
+  fi
+}
+
 # Setup process
 # TODO: make the header logo middle of the screen
 init_kit() {
@@ -248,34 +260,37 @@ init_kit() {
   fi
 
 
-  # Output SUPER variables (constants)
-  printf "K_KIT_NAME=\"%s\"\n"           "$kit_name"
-  printf "K_KIT_OWNER=\"%s\"\n"          "$kit_owner"
-  printf "K_KIT_SITE=\"%s\"\n"           "$kit_site"
-  printf "K_KIT_REPO=\"%s\"\n"           "$kit_repo"
-  printf "K_KIT_BRANCH=\"%s\"\n"         "$kit_repo_branch"
-  printf "K_KIT_INSTALLER_URL=\"%s\"\n"  "$kit_installer_url"
+  cat <<EOF
+export K_KIT_NAME="$kit_name"
+export K_KIT_OWNER="$kit_owner"
+export K_KIT_SITE="$kit_site"
+export K_KIT_REPO="$kit_repo"
+export K_KIT_BRANCH="$kit_repo_branch"
 
-  printf "K_KIT_DIR=\"%s\"\n"         "$kit_dir"
-  printf "K_LIB_DIR=\"%s\"\n"         "$lib_dir"
-  printf "K_INIT_FILE=\"%s\"\n"       "$init_file"
-  printf "K_PACKAGE_DIR=\"%s\"\n"     "$package_dir"
-  printf "K_ASSETS_DIR=\"%s\"\n"      "$assets_dir"
+export K_KIT_DIR="$kit_dir"
+export K_LIB_DIR="$lib_dir"
+export K_INIT_FILE="$init_file"
+export K_PACKAGE_DIR="$package_dir"
+export K_ASSETS_DIR="$assets_dir"
 
-  printf "K_PRJ_NAME=\"%s\"\n"        "$project_name"
-  printf "K_PRJ_OWNER=\"%s\"\n"       "$project_owner"
-  printf "K_PRJ_URL=\"%s\"\n"         "$project_url"
-  printf "K_PRJ_REPO=\"%s\"\n"        "$project_repo"
-  printf "K_PRJ_CONFIG=\"%s\"\n"      "$project_config_file"
+export K_KIT_INSTALLER_URL="$kit_installer_url"
+export K_KIT_VER_URL="$kit_ver_url"
+export K_KIT_UPSTREAM_VER_URL="$upstream_ver_url"
 
-  printf "K_CACHE_DIR=\"%s\"\n"       "$cache_dir"
-  printf "K_LOG_FILE=\"%s\"\n"        "$log_file"
+export K_PRJ_NAME="$project_name"
+export K_PRJ_OWNER="$project_owner"
+export K_PRJ_URL="$project_url"
+export K_PRJ_REPO="$project_repo"
+export K_PRJ_CONFIG="$project_config_file"
 
-  printf "K_KIT_VER_URL=\"%s\"\n"            "$kit_ver_url"
-  printf "K_KIT_UPSTREAM_VER_URL=\"%s\"\n"   "$upstream_ver_url"
-  printf "K_KIT_VERSION=\"%s\"\n"            "$(get_version)"
-  printf "K_KIT_UPSTREAM_VERSION=\"%s\"\n"   "$(get_version -u)"
-  printf "K_DEBUG_MODE=%s\n"                 "$debug_mode"
+export K_DEBUG_MODE=$debug_mode
+
+export K_CACHE_DIR="$cache_dir"
+export K_LOG_FILE="$log_file"
+
+export K_KIT_VERSION="$(get_version)"
+export K_KIT_UPSTREAM_VERSION="$(get_version -u)"
+EOF
 
   # Print source and check_dir commands
   printf "\nsleep 1\n"
@@ -295,20 +310,10 @@ init_kit() {
   printf "echo \" \\n \" \n"
   printf "log.success \"Initialization completed successfully.\" INIT\n"
   logf "Initialization complete."
+
   exit 0
 }
 
-run_tester() {
-  echo -e "\n${LAVENDER}================= KireiSakura Kit Test Utility ==================${NC}\n"
-
-  if bash "$lib_dir/_test.sh"; then
-    echo -e "\n\n${GREEN}================ TEST SUCCESSFULLY COMPLETED ==================${NC}\n"
-    exit 0
-  else
-    echo -e "\n\n${RED}================== TEST FAILED ==================${NC}\n"
-    exit 1
-  fi
-}
 
 #_________________________________ Default Configuration Values __________________________________________
 
