optimize codebase

diff --git a/bin/kireisakura b/bin/kireisakura
--- a/bin/kireisakura
+++ b/bin/kireisakura
@@ -74,9 +74,40 @@ show_help() {
 }
 
 # version
-show_version() {
+get_version() {
+  local url
+  local version
 
-  echo -e "\n  KireiSakura-Kit ${LAVENDER}v${verison}${NC}\n"
+  case "$1" in
+  -u | --upstream)
+    version=$(curl -s "$upstream_ver_url" || echo "N/A")
+    ;;
+  -l | --local)
+    version=$(cat "$kit_ver_url" || echo "N/A")
+    ;;
+  *)
+    version=$(cat "$kit_ver_url" || echo "N/A")
+    ;;
+  esac
+
+  if [[ "$version" == "N/A" ]]; then
+    return 1
+  fi
+
+  echo "$version"
+  return 0 
+}
+
+show_version() {
+  local version="$(get_version || echo "N/A")"
+
+  if [[ "$version" == "N/A" ]]; then
+    echo -e "  ${RED}Error: Unable to retrieve version.${NC}\n"
+    exit 1
+  else
+    echo -e "\n  KireiSakura-Kit ${LAVENDER}v${version}${NC}\n"
+    exit 0
+  fi
 }
 
 compare_num() {
@@ -115,15 +146,16 @@ update_kit() {
   local result
   local upstream_version
 
-  upstream_version="$(curl -sSL "$upstream_ver_url" || echo 0)"
+  upstream_version="$(get_version || echo 0)"
+
   [[ "$upstream_version" == "0" ]] && echo -e " ${RED}Couldn't resolve upstream version. Please check your connection or the URL.${NC}" || k_upstream_ver="$upstream_version"
 
-  result=$(compare_num "$kit_verison" "$k_upstream_ver")
+  result=$(compare_num "$kit_ver" "$upstream_version")
 
   if [ "$result" -eq 2 ]; then
     echo -e "\n  ${YELLOW}New update available:${NC} ${LAVENDER}v${verison} -> v${k_upstream_ver} ${NC}"
     echo -e " ${YELLOW}Updating....${NC}"
-    curl -L "$installer_url" | bash -s
+    curl -L "$kit_installer_url" | bash -s
 
   elif [[ $result -eq 0 ]]; then
     echo -e "\n  ${GREEN}No new update available.${NC}"
@@ -141,15 +173,14 @@ update_kit() {
 # TODO: make the header logo middle of the screen
 init_kit() {
   local kit_version
-  local header="$(cat $k_assets_dir/header.txt)"
-
+  
   printf "\n\n" >>"$log_file"
   logf "====================== NEW SESSION =======================\n"
   logf "Started in: $(pwd)/"
   logf "Initialization started."
 
   printf "clear\n"
-  printf "echo -e '%*s'\n" $(((${#header} + columns) / 2)) "$header"
+  printf "command -v figlet >/dev/null 2>&1 && figlet \"%s\" || cat \"\$k_assets_dir/header.txt\"\n" "$project_name"
   printf "echo -e '\\\n\\\n%s[ INIT ]-> Starting Initialization..%s\\\n\\\n'\n" "$YELLOW" "$NC"
 
   [[ "$config_file" == "NULL" ]] || printf "echo -e '%s[✔]-> Loaded Config file..%s'\n" "$GREEN" "$NC"
@@ -167,7 +198,7 @@ init_kit() {
     printf "echo -e '%s[!]-> Validating....%s'\n" "$YELLOW" "$NC"
   fi
 
-  if [ ! -d "$k_dir" ]; then
+  if [ ! -d "$kit_dir" ]; then
     if [ "$is_cstm_kit_dir" = true ]; then
       logf "Error: given custom kit dir is not valid."
       printf "echo -e '%s[X]-> Error: Custom Kit directory does not exist. Please check given directory path.%s\n'" "$RED" "$NC"
@@ -184,53 +215,67 @@ init_kit() {
       logf "Custom kit dir exists."
       printf "echo -e '%s[✔]-> Custom Kit directory exists.%s'\n" "$GREEN" "$NC"
     else
-      echo -e "echo -e \"${GREEN}[✔]-> Validated default installation.${NC}\""
+      echo -e "echo -e \"\${GREEN}[✔]-> Validated default installation.${NC}\""
       echo
     fi
   fi
 
   # Check if core file exists
-  if [ ! -f "$k_loader" ]; then
+  if [ ! -f "$loader_file" ]; then
     logf "Error: Core file is missing in kit."
     printf "echo -e '%s[X]-> Error: Core file is missing in Kit. Please check installation or re-install.%s\n'" "$RED" "$NC"
     printf "echo -e 'Exiting.....' \n"
     exit 1
   fi
 
-  kit_version=$(cat "$k_dir"/.version)
 
   # Output SUPER variables
-  printf "k_dir=\"%s\"\n" "$k_dir"
-  printf "k_core_dir=\"%s\"\n" "$k_core_dir"
-  printf "k_loader=\"%s\"\n" "$k_loader"
-  printf "k_package_dir=\"%s\"\n" "$k_package_dir"
-  printf "k_assets_dir=\"%s\"\n" "$k_assets_dir"
-  printf "k_docs_url=\"%s\"\n" "$docs_url"
+  printf "k_kit_name=\"%s\"\n"           "$kit_name"
+  printf "k_kit_owner=\"%s\"\n"          "$kit_owner"
+  printf "k_kit_site=\"%s\"\n"           "$kit_site"
+  printf "k_kit_repo=\"%s\"\n"           "$kit_repo"
+  printf "k_kit_branch=\"%s\"\n"         "$kit_repo_branch"
+  printf "k_kit_installer_url=\"%s\"\n"  "$kit_installer_url"
 
-  printf "k_prj_name=\"%s\"\n" "$project_name"
-  printf "k_cache_dir=\"%s\"\n" "$cache_dir"
-  printf "k_log_file=\"%s\"\n" "$log_file"
-  printf "k_kit_version=\"%s\"\n" "$kit_version"
+  printf "k_kit_dir=\"%s\"\n"         "$kit_dir"
+  printf "k_core_dir=\"%s\"\n"        "$core_dir"
+  printf "k_loader=\"%s\"\n"          "$loader_file"
+  printf "k_package_dir=\"%s\"\n"     "$package_dir"
+  printf "k_assets_dir=\"%s\"\n"      "$assets_dir"
+
+  printf "k_prj_name=\"%s\"\n"        "$project_name"
+  printf "k_prj_owner=\"%s\"\n"       "$project_owner"
+  printf "k_prj_url=\"%s\"\n"         "$project_url"
+  printf "k_prj_repo=\"%s\"\n"        "$project_repo"
+  printf "k_prj_config=\"%s\"\n"      "$project_config_file"
+
+  printf "k_cache_dir=\"%s\"\n"       "$cache_dir"
+  printf "k_log_file=\"%s\"\n"        "$log_file"
+
+  printf "k_kit_ver_url=\"%s\"\n"            "$kit_ver_url"
+  printf "k_kit_upstream_ver_url=\"%s\"\n"   "$upstream_ver_url"
+  printf "k_kit_version=\"%s\"\n"            "$(get_version)"
+  printf "k_kit_upstream_version=\"%s\"\n"   "$(get_version -u)"
 
   # Print source and check_dir commands
-  printf "sleep 1\n"
+  printf "\nsleep 1\n"
   logf "Loading core....."
   printf "echo -e \"%s[!]-> Loading core.%s\" \n" "$YELLOW" "$NC"
   printf "source \"\$k_loader\" \n"
   printf "log.success 'Loaded core.' \n"
   logf "Loaded core."
 
-  # This was the issue part
   printf "sleep 1\n"
   printf "log.warn \"Checking cache directory.....\"\n"
   printf "check-dir \"\${k_cache_dir}\" --needed\n"
   printf "log.success \"Cache directory exists.\"\n"
-  printf "echo "" \n"
-  printf "log \"KireiSakura-Kit v%s\"  \n" "$kit_version"
+  printf "echo \n"
+  printf "log \"KireiSakura-Kit v%s\"  \n" "$(get_version)"
   printf "sleep 1\n"
   printf "echo \" \\n \" \n"
   printf "log.success \"Initialization complete.\" INIT\n"
   logf "Initialization complete."
+  exit 0
 }
 
 run_tester() {
@@ -238,50 +283,49 @@ run_tester() {
 
   if bash "$core_dir/_test.sh"; then
     echo -e "\n\n${GREEN}================ TEST SUCCESSFULLY COMPLETED ==================${NC}\n"
+    exit 0
   else
     echo -e "\n\n${RED}================== TEST FAILED ==================${NC}\n"
+    exit 1
   fi
 }
 
 #_________________________________ Default Configuration Values __________________________________________
 
+# Super variables
+kit_name="KireiSakura-Kit"                 # k_kit_name
+kit_owner="soymadip"                       # k_kit_owner
+kit_site="https://kireisakura.soymadip.me" # k_kit_site
+kit_repo="${kit_owner}/${kit_name}"        # k_kit_repo
+kit_repo_branch="main"                     # k_kit_branch
+
+kit_dir="$HOME/.local/share/${kit_name}"   # k_kit_dir
+core_dir="$kit_dir/core"                   # k_core_dir
+loader_file="$core_dir/_loader.sh"         # k_loader
+package_dir="$kit_dir/packages"            # k_package_dir
+assets_dir="$kit_dir/Assets"               # k_assets_dir
+
+kit_ver_url="$kit_dir/.version"           # k_kit_ver_url
+kit_installer_url="${kit_site}/install"   # k_kit_installer_url
+upstream_ver_url="$kit_site/version"      # k_kit_upstream_ver_url
+
+project_name="$kit_name"            # k_prj_name
+project_owner="$kit_owner"          # k_prj_owner
+project_url="$kit_site"             # k_prj_url
+project_repo="$kit_repo"            # k_prj_repo
+project_config_file="config.yml"    # k_prj_config
+
+cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/${project_name}" # k_cache_dir
+log_file="${cache_dir}/${project_name}.log"                 # k_log_file
+
+
+# ____________________________________ Main _________________________________________________
+
 # source colors
 eval "$("$(dirname "$0")/../core/_colors.sh")"
 
-# Define Super variables
-
-kit_name="KireiSakura-Kit"                # k_kit_name
-kit_owner="soymadip"                      # k_kit_owner
-kit_url="https://kireisakura.soymadip.me" # k_kit_url
-kit_repo="${kit_owner}/${kit_name}"       # k_kit_repo
-kit_repo_branch="main"                    # k_kit_branch
-
-project_name="$kit_name"         # k_prj_name
-project_owner="$kit_owner"       # k_prj_owner
-project_url="$kit_url"           # k_prj_url
-project_repo="$kit_repo"         # k_prj_url
-project_config_file="config.yml" # k_prj_config
-
-kit_dir="$HOME/.local/share/${kit_name}" # k_kit_dir
-core_dir="$kit_dir/core"                 # k_core_dir
-loader_file="$core_dir/_loader.sh"       # k_loader
-package_dir="$kit_dir/packages"          # k_package_dir
-assets_dir="$kit_dir/Assets"             # k_package_dir
-kit_ver="$(cat "$kit_dir"/.version)"     # k_kit_version
-
-cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/${project_name}" # k_cache_dir
-log_file="${cache_dir}/${project_name}.log"                 # k_cache_dir
-
-upstream_ver_url="https://raw.githubusercontent.com/${kit_repo}/${kit_repo_branch}/.version"
-
-#
-# ____________________________________ Main _________________________________________________
-
-# If no arguments
-[ "$#" -eq 0 ] && show_man
-
 # Parse option
-while [[ "$#" -gt 0 ]]; do
+while [[ "$#" -ge 0 ]]; do
 
   case "$1" in
   -h | --help)
@@ -297,6 +341,7 @@ while [[ "$#" -gt 0 ]]; do
     run_tester
     ;;
   -i | --init)
+    mkdir -p "$cache_dir"
     init_kit
     ;;
   *)
